default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: c2sadmin
  password: 1234
  host: localhost

development:
  <<: *default
  database: c2s-development

test:
  <<: *default
  database: c2s-test

production:
  <<: *default
  database: c2s-production
  username: c2sadmin
  password: 1234